### PR TITLE
Show only groups in Og audience field settings

### PR DESCRIPTION
**Pull request by amitaibu**
This is cherry picked out of #181

PR also removed some obsolete schema settings.

### CODE REVIEW

**Comment by amitaibu** [comment]
For example, the `Article` bundle was filtered out

groups_audience_settings_for_article___site-install

**Comment by amitaibu** [comment]
Needs a Kernel test of course :)

**Comment by amitaibu** [comment]
hmm, I don't see Kernel tests for forms in core - ones that tests forms that are created outside of the test itself. So I might opt for a Functional test instead.

**Comment by amitaibu** [comment]
@liatsade fyi, this PR has a [Functional](https://github.com/Gizra/og/pull/203/files#diff-488dae2ab638f67a4970ccc28f809895R1) automatic test.

**Comment by amitaibu** [comment]
Update: Test is passing locally, but fails on Travis :/

**Comment by amitaibu** [comment]
Update: Trying to debug the tests on Travis, it [shows](https://travis-ci.org/Gizra/og/jobs/168748844#L574) that it gets a 404 on that page. 
It works locally, so  I wonder what it can be.

**Comment by amitaibu** [comment]
@pfrenssen have you ever stumbled upon such a case?

(btw, I will of course rebase all those debug commits)

**Comment by amitaibu** [comment]
First hint, [seems](https://travis-ci.org/Gizra/og/builds/168762632#L562) the user doesn't have access to that route (again, even-though it works on my local).

**Comment by amitaibu** [comment]
@pfrenssen Ignore for now, I'm checking the access stuff based on the above hint.

**Comment by amitaibu** [comment]
@pfrenssen nope, not access :/. Anyway, if you happen to have seen something like this..

**Comment by amitaibu** [comment]
@nirgn975 if I had Travis [running a docker](http://www.gizra.com/content/docker-travis-ci/) it would be really helpful, as this debug turns out to be very hard. Can you look at this please in contribution hour?

**Comment by amitaibu** [comment]
(as a different PR)

**Comment by amitaibu** [comment]
@klausi do you happen to know [this](https://github.com/Gizra/og/pull/203#issuecomment-254640091) problem? Seems core does it with SimpleTest, but I prefer to use PHPunit.

**Comment by klausi** [comment]
Looks like the response comes from the PHP webserver. Probably it cannot deal with the "." in the URL? Time to use a real web server like apache or nginx?

**Comment by amitaibu** [comment]
@klausi sounds like a good guess! I wish I would have thought about it as-well too many hours ago 😉

**Comment by amitaibu** [comment]
I've converted test to Kernel, and merged it back to #181 - as otherwise it would have required fixes to code that is soon going to be deleted anyway.

**Pull request closed without merging**
