### PR TITLE
Add the ability to remove and adjust existing routes in OgAdminRoutesEventInterface

### PR DESCRIPTION
**Pull request by webflo**
I think its currently not possible to add or alter existing routes to the route list. Expanded the interface to match the documentation.

### CODE REVIEW

**Comment by webflo** [comment]
// cc @pfrenssen: I will write a patch for OG Menu that add all OG Menus to the admin route list of a group.

**Comment by pfrenssen** [comment]
Change looks good, the `OgEventSubscriber` was overwriting the full paths instead of altering the existing ones. I also like the function name changes.

There is a coding standards violation, but for the rest this looks good to me.

**Comment by amitaibu** [comment]
Ha, @webflo , we meet at each others repos 😄

**Comment by amitaibu** [comment]
Thanks!

**Pull request merged**
