### PR TITLE
Remove unused og.og_permissions.yml

### LINKED ISSUE #347: Remove outdated `og.og_permissions.yml` file
We still have the legacy YAML file that contains the OG permissions from our initial implementation: `og.og_permissions.yml`. This is no longer used, the permissions are now declared in `OgEventSubscriber::provideDefaultOgPermissions()`.

We should remove this file since it can confuse developers who might think that this is the way to declare permissions.

### PR DESCRIPTION
**Pull request by zerolab**
Fixes #347

### CODE REVIEW

**Comment by geertvd** [comment]
I think `OgNodePermissions` can also be removed

**Comment by zerolab** [comment]
Nice catch, @geertvd. Sorted

**Comment by geertvd** [comment]
This looks good now

**Comment by zerolab** [comment]
@pfrenssen this is a quick simple one that is ready to go

**Comment by pfrenssen** [comment]
Looks good, thanks!

**Pull request merged**
