### PR TITLE
Consolidate the permissions regarding roles and permissions.

### LINKED ISSUE #526: Consider to unify permissions for managing roles and permissions in `administer permissions`
In Drupal 7 we had two separate permissions for managing roles and permissions: `manage roles` and `manage permissions`.

However these are very closely related since editing a role also allows the editing of the role's permissions, and a user with `manage permissions` can edit the permissions of all roles.

Both UIs are also very closely related, the role UI showing the permissions in a single column of checkboxes, while the permissions UI shows the same thing but in a matrix that covers all roles.

I would propose to do this in the same way as it is handled in Drupal core: with a single `administer permissions` permission that grants access to both.

### PR DESCRIPTION
**Pull request by pfrenssen**
Fixes #526

### CODE REVIEW

**Comment by zerolab** [comment]
That looks good, but should there be a hook_update to prevent existing projects from tripping up?

**Comment by pfrenssen** [comment]
We're in alpha so we are not yet considered to be stable and do not have to write update hooks. These permissions are also not yet used anywhere.

**Comment by zerolab** [comment]
Fair enough.

Our project made use of at least one of them, so at least the release notes should include something for it, imho

**Comment by MPParsley** [comment]
Perhaps we can start to [keep a changelog](https://keepachangelog.com/en/1.0.0/)? #531

**Comment by pfrenssen** [comment]
I don't think changelogs are so useful since the invention of version control systems :) We already mention all the changes in the release notes.

**Comment by MPParsley** [comment]
> I don't think changelogs are so useful since the invention of version control systems :) We already mention all the changes in the release notes.

Toh, just opened #532 :-) And yes, I noticed that all changes have been properly addressed in the releases on github. Not sure how this will evolve when contrib is to be maintained on gitlab though (if we ever move there)?

**Comment by pfrenssen** [comment]
We did not make plans yet to move to Gitlab but this is something that is very interesting, especially if we can keep running our custom CI pipelines.

**Review by MPParsley — APPROVED** [review]
Not sure if a hook_update would have been sufficient since we're removing the old permission.

Anyhow alpha & not yet used so if we want to do this we'd better do it now.

**Pull request merged**
