### PR TITLE
Issue #2540690: Incorrect comparison of OG_CONTENT_ACCESS_FIELD

### PR DESCRIPTION
**Pull request by angarsky**
Hi!

I created an issue at d.org - https://www.drupal.org/node/2540690.
@amitaibu asked me to cover my code by tests - I did it. Please, review my PR.
All explanations for this bug you will find in issue at d.org. I know that 1 test (OgFieldWidgetTestCase) is failed, but it's not connected with my patch.

### CODE REVIEW

**Comment by amitaibu** [comment]
Thanks, blocked by #134

**Comment by angarsky** [comment]
Hi, @amitaibu! Is the issue with Travis solved? Is it possible to re-run tests?

**Comment by alesrebec** [comment]
Looks like we still have issues running tests.

https://travis-ci.org/Gizra/og/jobs/393649128

`Command core-quick-drupal was not found.`

/cc @amitaibu @AronNovak

**Comment by amitaibu** [comment]
@AronNovak when you get a chance to have a look please.

**Comment by claudiu-cristea** [comment]
Since https://www.drupal.org/project/og/issues/3467694 was merged into the `8.x-1.x` branch, the development has been moved to https://www.drupal.org/project/og. If this change is still actual, please open an issue at https://www.drupal.org/project/issues/og and provide there a _merge request_ similar with this pull request.

Thank you for contributing to Organic groups module.

**Pull request closed without merging**
