### PR TITLE
Add default access check

### PR DESCRIPTION
**Pull request by pebosi**
See: https://www.drupal.org/project/og/issues/2810795

### CODE REVIEW

**Comment by amitaibu** [comment]
Thanks. Can you please attach a screenshot demonstrating the change of access

**Comment by amitaibu** [comment]
Actually, it looks good. Thanks!

**Comment by pfrenssen** [comment]
I wonder why the `access content` permission was chosen instead of `access user profiles`? This view is displaying user profiles, not nodes.

**Comment by amitaibu** [comment]
You might be right, but I think it's not a case that it's very clear. I wouldn't mind changing it to `access user profiles`.

**Comment by MPParsley** [comment]
Closed https://www.drupal.org/project/og/issues/2810795

**Pull request merged**
