### PR TITLE
Sort permission list to avoid noise on config export

### PR DESCRIPTION
**Pull request by claudiu-cristea**
Drupal.org issue https://www.drupal.org/project/og/issues/3441122. I've opened a MR also on drupal.org. No idea which is the canonical location.

### CODE REVIEW

**Comment by amitaibu** [comment]
Thanks

> No idea which is the canonical location.

At the time (6h years ago) there was  no proper PR review, so we moved to GitHub. I think we can move back to Drupal and Gitlab. @MPParsley @pfrenssen what do you think?

We can then deal with only a single CI :smiling_imp:

**Comment by joelpittet** [comment]
I know I haven't done much with my comaintainership but back in d.o gitlab would be my preference. "With the rest of the fire 🔥" - Morris Moss

**Comment by amitaibu** [comment]
@claudiu-cristea would you have time to have a look at the failing tests?

**Comment by amitaibu** [comment]
@bboro ^^

**Comment by claudiu-cristea** [comment]
@amitaibu, I’ve created https://www.drupal.org/project/og/issues/3467694 to run tests on drupal.org GitLab CI and archive this repository. The issue is ready for review

**Comment by claudiu-cristea** [comment]
@amitaibu forgot to mention that prior review, 8.x-1.x branch needs to be aligned from GitHub to drupal.org. It contains last commit not synchronized. I'm not a maintainer, could you, please, help?

**Comment by amitaibu** [comment]
Sure, done 

image

**Comment by claudiu-cristea** [comment]
Thank you

**Comment by claudiu-cristea** [comment]
Since https://www.drupal.org/project/og/issues/3467694 was merged into the `8.x-1.x` branch, the development has been moved to https://www.drupal.org/project/og. If this change is still actual, please open an issue at https://www.drupal.org/project/issues/og and provide there a _merge request_ similar with this pull request.

Thank you for contributing to Organic groups module.

**Pull request closed without merging**
