### PR TITLE
[BUGFIX] og membership access should use og_user_access.

### PR DESCRIPTION
**Pull request by ordavidil**

### CODE REVIEW

**Comment by amitaibu** [comment]
Can we have a simpleTest to assert this please

**Comment by Xilis** [comment]
Why should it use og_user_access? There is a comment right above that line, stating
 `// No-end user needs access to this entity, so restrict it to admins.`

**Comment by Xilis** [comment]
Found some more related issues, maybe something like https://www.drupal.org/project/og/issues/2583303 goes in a better direction?

**Comment by claudiu-cristea** [comment]
Since https://www.drupal.org/project/og/issues/3467694 was merged into the `8.x-1.x` branch, the development has been moved to https://www.drupal.org/project/og. If this change is still actual, please open an issue at https://www.drupal.org/project/issues/og and provide there a _merge request_ similar with this pull request.

Thank you for contributing to Organic groups module.

**Pull request closed without merging**
