### PR TITLE
Fix PHP CS issues

### PR DESCRIPTION
**Pull request by MPParsley**
Seems like there's been an update to phpcs;

```
PHP CodeSniffer Config installed_paths set to ../../drupal/coder/coder_sniffer,../../sirbrillig/phpcs-variable-analysis,../../slevomat/coding-standard
........EEE..................E..E.......E....E.....E.E......  60 / 201 (30%)
......EE.E....E.....E...E.......EW.......................... 120 / 201 (60%)
...............................W.EEWW.............E......E.. 180 / 201 (90%)
E.........W.........W                                        201 / 201 (100%)
FILE: /home/travis/build/Gizra/og/tests/src/Functional/GroupTabTest.php
--------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
--------------------------------------------------------------------------------
 68 | ERROR | The array declaration line has 89 characters (the limit is 80).
    |       | The array content should be split up over multiple lines
 71 | ERROR | The array declaration line has 89 characters (the limit is 80).
    |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: ...travis/build/Gizra/og/tests/src/Functional/GroupSubscribeFormatterTest.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 69 | ERROR | The array declaration line has 96 characters (the limit is 80).
    |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/tests/src/Unit/GroupTypeManagerTest.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 229 | ERROR | The array declaration line has 95 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: ...ome/travis/build/Gizra/og/tests/src/Unit/OgResolvedGroupCollectionTest.php
--------------------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 4 LINES
--------------------------------------------------------------------------------
  33 | ERROR | The array declaration line has 89 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
  80 | ERROR | The array declaration line has 83 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
  95 | ERROR | The array declaration line has 91 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
 108 | ERROR | The array declaration line has 91 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: .../og/tests/src/Unit/Plugin/OgGroupResolver/OgRouteGroupResolverTestBase.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 96 | ERROR | The array declaration line has 89 characters (the limit is 80).
    |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/tests/src/Unit/GroupSubscribeFormatterTest.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 344 | ERROR | The array declaration line has 146 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: ...travis/build/Gizra/og/tests/src/Kernel/Access/AccessByOgMembershipTest.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 137 | ERROR | The array declaration line has 90 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: ...s/src/Kernel/EntityReference/Views/OgStandardReferenceRelationshipTest.php
--------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
--------------------------------------------------------------------------------
 68 | ERROR | The array declaration line has 214 characters (the limit is 80).
    |       | The array content should be split up over multiple lines
 71 | ERROR | The array declaration line has 218 characters (the limit is 80).
    |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/tests/src/Kernel/Action/ActionTestBase.php
--------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
--------------------------------------------------------------------------------
 165 | ERROR | The array declaration line has 191 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
 169 | ERROR | The array declaration line has 164 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: ...me/travis/build/Gizra/og/tests/src/Kernel/Entity/GetBundleByBundleTest.php
--------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
--------------------------------------------------------------------------------
 294 | ERROR | The array declaration line has 82 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
 514 | ERROR | The array declaration line has 82 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
 525 | ERROR | The array declaration line has 82 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/tests/src/Kernel/Entity/GetMembershipsTest.php
--------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
--------------------------------------------------------------------------------
 104 | ERROR | The array declaration line has 81 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
 108 | ERROR | The array declaration line has 83 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: ...e/travis/build/Gizra/og/tests/src/Kernel/Entity/EntityCreateAccessTest.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 109 | ERROR | The array declaration line has 83 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: ...avis/build/Gizra/og/tests/src/Kernel/Entity/GroupMembershipManagerTest.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 237 | ERROR | The array declaration line has 100 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/tests/src/Kernel/Entity/GetUserGroupsTest.php
--------------------------------------------------------------------------------
FOUND 5 ERRORS AFFECTING 5 LINES
--------------------------------------------------------------------------------
 212 | ERROR | The array declaration line has 144 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
 223 | ERROR | The array declaration line has 143 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
 236 | ERROR | The array declaration line has 143 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
 286 | ERROR | The array declaration line has 168 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
 290 | ERROR | The array declaration line has 167 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: ...avis/build/Gizra/og/tests/src/Kernel/Plugin/Block/MemberCountBlockTest.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 136 | ERROR | The array declaration line has 82 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/src/Controller/SubscriptionController.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 103 | ERROR | The array declaration line has 83 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/src/Controller/OgAdminMembersController.php
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------
 13 | WARNING | The class short comment should describe what the class does and
    |         | not simply repeat the class name
--------------------------------------------------------------------------------
FILE: ...avis/build/Gizra/og/src/Plugin/Field/FieldType/OgStandardReferenceItem.php
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------
 23 | WARNING | The class short comment should describe what the class does and
    |         | not simply repeat the class name
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/src/Plugin/Field/FieldWidget/OgComplex.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 113 | ERROR | The array declaration line has 104 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: ...build/Gizra/og/src/Plugin/Field/FieldFormatter/GroupSubscribeFormatter.php
--------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
--------------------------------------------------------------------------------
 146 | ERROR | The array declaration line has 115 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
 148 | ERROR | The array declaration line has 118 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/src/Plugin/Derivative/OgLocalTask.php
-----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
-----------------------------------------------------------------------
 80 | WARNING | Unused variable $entry.
-----------------------------------------------------------------------
FILE: ...in/Validation/Constraint/ValidOgMembershipReferenceConstraintValidator.php
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------
 20 | WARNING | [x] Inline @var declarations should use the /** */ delimiters
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/src/Plugin/Condition/GroupType.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 142 | ERROR | The array declaration line has 135 characters (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/src/Plugin/OgDeleteOrphans/Batch.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 61 | ERROR | The array declaration line has 85 characters (the limit is 80).
    |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/src/Plugin/Block/RecentGroupContentBlock.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AND 1 WARNING AFFECTING 2 LINES
--------------------------------------------------------------------------------
 222 | ERROR   | The array declaration line has 90 characters (the limit is
     |         | 80). The array content should be split up over multiple lines
 246 | WARNING | FieldStorageConfig::loadMultiple calls should be avoided in
     |         | classes, use dependency injection instead
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/src/MembershipManager.php
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------
 383 | WARNING | FieldStorageConfig::loadMultiple calls should be avoided in
     |         | classes, use dependency injection instead
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/og.views.inc
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------
 63 | WARNING | [x] A comma should follow the last multiline array item. Found:
    |         |     )
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------
Time: 4.6 secs; Memory: 18MB

```

### CODE REVIEW

**Comment by pfrenssen** [comment]
Wow there are a whole lot of them!

**Comment by pfrenssen** [comment]
I made a bit of progress on this but we are affected by a false positive:

```
FILE: /home/pieter/v/contrib/og/src/Plugin/Derivative/OgLocalTask.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 80 | WARNING | Unused variable $entry.
----------------------------------------------------------------------
```

This is thrown for this code, but the variable `$entry` is used since it modifies the parent array by reference:
```
    foreach ($derivatives as &$entry) {
      $entry += $base_plugin_definition;
    }
```

The sniff that throws the false positive is `DrupalPractice.CodeAnalysis.VariableAnalysis.UnusedVariable`. I have apparently already reported this some time ago in [Issue #3065679: False positive for unused variable when variable is passed by reference in closure](https://www.drupal.org/project/coder/issues/3065679).

I started looking into it but I ran out of my contribution time before making any meaningful progress.

**Comment by bboro** [comment]
Just a thought, would the non-shorthand version get us through the hurdle? It may not be ideal but something like:

`$entry = $entry + $base_plugin_definition;`

**Comment by pfrenssen** [comment]
Oh yes it would help OG in this particular instance, but our code is valid, the bug is in the coder module.

I'm doing this in my spare time and in my personal philosophy I prefer to spend my time to fix the root of the problem in the Coder module so that this is fixed not only for us but for the whole Drupal ecosystem. Especially since this already affected me before in some project.

If this would affect my work project I would be happy with a quick fix, but for me personally fixing this is not super urgent :) I was just working on this because it is now blocking some important PRs like #692

**Comment by pfrenssen** [comment]
I think in this case it would perhaps be a good idea to skip those failing lines that are affected by the false positive, or even disable the faulty sniff entirely.

**Comment by MPParsley** [comment]
Reported the issue in https://github.com/sirbrillig/phpcs-variable-analysis/issues/219.

@pfrenssen, this may take some time to get resolved. Personally, I find the sniff `DrupalPractice.CodeAnalysis.VariableAnalysis.UnusedVariable` quite useful so I'd be ok with the workaround stated by @bboro. Otoh we could also temprariliy disable that sniff.

Seems that in the meanwhile another issue with phpunit appeared.

```
PHP Fatal error:  Trait 'Prophecy\PhpUnit\ProphecyTrait' not found in /home/travis/build/Gizra/drupal/core/tests/Drupal/TestTools/PhpUnitCompatibility/PhpUnit9/TestCompatibilityTrait.php on line 12
```

**Comment by pfrenssen** [comment]
We can ignore those failing lines that are affected by the false positive, by putting a comment `phpcs:ignore` or `phpcs:disable`. See https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file

**Comment by MPParsley** [comment]
Still some sniffs complaining:
```
PHP CodeSniffer Config installed_paths set to ../../drupal/coder/coder_sniffer,../../sirbrillig/phpcs-variable-analysis,../../slevomat/coding-standard
............W......................................E.E......  60 / 201 (30%)
......EE.E....E.....E....................................... 120 / 201 (60%)
..............W..................W.W........................ 180 / 201 (90%)
......W...W.....W....                                        201 / 201 (100%)
FILE: /home/travis/build/Gizra/og/tests/src/Unit/OgAccessTestBase.php
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------
 176 | WARNING | [x] '@todo: Move to test.' should match the format '@todo Fix
     |         |     problem X here.'
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------
FILE: ...s/src/Kernel/EntityReference/Views/OgStandardReferenceRelationshipTest.php
--------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
--------------------------------------------------------------------------------
 68 | ERROR | The array declaration extends to column 212 (the limit is 80).
    |       | The array content should be split up over multiple lines
 71 | ERROR | The array declaration extends to column 216 (the limit is 80).
    |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/tests/src/Kernel/Action/ActionTestBase.php
--------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
--------------------------------------------------------------------------------
 165 | ERROR | The array declaration extends to column 189 (the limit is 80).
     |       | The array content should be split up over multiple lines
 169 | ERROR | The array declaration extends to column 162 (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: ...me/travis/build/Gizra/og/tests/src/Kernel/Entity/GetBundleByBundleTest.php
--------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
--------------------------------------------------------------------------------
 294 | ERROR | The array declaration extends to column 81 (the limit is 80).
     |       | The array content should be split up over multiple lines
 514 | ERROR | The array declaration extends to column 81 (the limit is 80).
     |       | The array content should be split up over multiple lines
 525 | ERROR | The array declaration extends to column 81 (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/tests/src/Kernel/Entity/GetMembershipsTest.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 108 | ERROR | The array declaration extends to column 82 (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: ...e/travis/build/Gizra/og/tests/src/Kernel/Entity/EntityCreateAccessTest.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 109 | ERROR | The array declaration extends to column 82 (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: ...avis/build/Gizra/og/tests/src/Kernel/Entity/GroupMembershipManagerTest.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 237 | ERROR | The array declaration extends to column 90 (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/tests/src/Kernel/Entity/GetUserGroupsTest.php
--------------------------------------------------------------------------------
FOUND 5 ERRORS AFFECTING 5 LINES
--------------------------------------------------------------------------------
 212 | ERROR | The array declaration extends to column 141 (the limit is 80).
     |       | The array content should be split up over multiple lines
 223 | ERROR | The array declaration extends to column 140 (the limit is 80).
     |       | The array content should be split up over multiple lines
 236 | ERROR | The array declaration extends to column 140 (the limit is 80).
     |       | The array content should be split up over multiple lines
 286 | ERROR | The array declaration extends to column 124 (the limit is 80).
     |       | The array content should be split up over multiple lines
 290 | ERROR | The array declaration extends to column 124 (the limit is 80).
     |       | The array content should be split up over multiple lines
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/src/Og.php
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------
 83 | WARNING | [x] '@todo: Verify this is still needed here.' should match the
    |         |     format '@todo Fix problem X here.'
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/src/Plugin/Field/FieldWidget/OgComplex.php
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------
 35 | WARNING | [x] 'todo: fix the definition in th UI level.' should match the
    |         |     format '@todo Fix problem X here.'
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/src/Plugin/Derivative/OgLocalTask.php
-----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
-----------------------------------------------------------------------
 85 | WARNING | Unused variable $entry.
-----------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/src/GroupTypeManager.php
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------
 271 | WARNING | [x] '@todo, just key by bundle ID instead?' should match the
     |         |     format '@todo Fix problem X here.'
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/src/MembershipManager.php
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------
 383 | WARNING | FieldStorageConfig::loadMultiple calls should be avoided in
     |         | classes, use dependency injection instead
--------------------------------------------------------------------------------
FILE: /home/travis/build/Gizra/og/og_ui/src/Form/AdminSettingsForm.php
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------
 86 | WARNING | [x] '@todo: Port og_ui_admin_people_view.' should match the
    |         |     format '@todo Fix problem X here.'
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------
```

**Comment by MPParsley** [comment]
@pfrenssen or @amitaibu, tests are green. This one's ready for review.

**Review by amitaibu — APPROVED** [review]
Thank you for working on that!

**Comment by amitaibu** [comment]
Merged, and pushed to d.o.

**Pull request merged**
