### PR TITLE
3306494: add support to get membership from group node.

### PR DESCRIPTION
**Pull request by webdobe**
Link to drupal issue:
https://www.drupal.org/project/og/issues/3306494

Basically, this allows to create a view of content a user is a member of.

### CODE REVIEW

**Comment by lozeone** [comment]
I think the code here is a better approach https://github.com/Gizra/og/issues/752

**Comment by pwolanin** [comment]
Does this assume that only nodes are groups?

**Comment by lozeone** [comment]
The PR in #756 will work for any entity that enabled as an og group

**Comment by claudiu-cristea** [comment]
Since https://www.drupal.org/project/og/issues/3467694 was merged into the `8.x-1.x` branch, the development has been moved to https://www.drupal.org/project/og. If this change is still actual, please open an issue at https://www.drupal.org/project/issues/og and provide there a _merge request_ similar with this pull request.

Thank you for contributing to Organic groups module.

**Pull request closed without merging**
