### PR TITLE
Signature of EventDispatcherInterface::dispatch() has changed

### LINKED ISSUE #725: Fix event dispatcher BC
The arguments to the event dispatcher are backwards compared to expected (some BC code in Symfony is allowing it for now):

`    $this->eventDispatcher->dispatch(GroupCreationEventInterface::EVENT_NAME, $event);
`

3:55
that’s in several places (the reversed arguments) (edited)

### PR DESCRIPTION
**Pull request by pfrenssen**
In Drupal 9.1 the order of the arguments to this method has been changed.

Ref. [Change record #3154407: Signature of EventDispatcherInterface::dispatch() has changed](https://www.drupal.org/node/3154407)

Fixes #725.

This also updates the touched classes with modern practices, such as introducing missing type hints, and some small unrelated fixes.

### CODE REVIEW

**Comment by pfrenssen** [comment]
This is failing on PHP 7.3 because it introduces typed properties which are PHP7.4+. Let's block this on #732 which increases our minimum PHP requirement to 7.4.

**Comment by pfrenssen** [comment]
Nice, the type hints that were added have uncovered some bugs in the `BundleFormAlter` class. It indeed looks like this is some very early code that is not following correct OO practices, and has mixed up some things like entity IDs and bundles.

I will handle this in a separate PR.

**Comment by claudiu-cristea** [comment]
@pfrenssen this is handler already in the [D10 compatibility](https://github.com/Gizra/og/pull/754) PR. This should be closed.

**Comment by amitaibu** [comment]
Closing, based on https://github.com/Gizra/og/pull/733#issuecomment-1321122406

**Pull request closed without merging**
