### PR TITLE
Remove  parameter from Og::invalidateCache()

### PR DESCRIPTION
**Pull request by alvar0hurtad0**

### CODE REVIEW

**Comment by alvar0hurtad0** [comment]
Parent issue #234

**Comment by pfrenssen** [comment]
This looks good! Thanks!

This is ready to be merged but we appear to have an unrelated failure. We'll have to postpone this for a bit until that is fixed.

**Comment by alvar0hurtad0** [comment]
Yes... I found it

`use Drupal\Console\Core\Style\DrupalStyle;`

running test on local to ensure it works on next push.

Thanks

**Comment by pfrenssen** [comment]
It was fixed in #230 which is merged now. Could you merge in the latest 8.x-1.x and try again?

**Comment by pfrenssen** [comment]
:+1:

**Comment by alvar0hurtad0** [comment]
Too late :)

**Comment by pfrenssen** [comment]
Still a DrupalConsole related failure. It happens only on Drupal 8.2 and has to do with composer dependencies. This is out of scope for this issue though.

I'm going to Drupalcamp Plovdiv tomorrow and am intending to sprint, I'll try to take a look at it then.

**Comment by alvar0hurtad0** [comment]
It seems there's a problem with dependencies.

I've created a PR on Console 

https://github.com/hechoendrupal/drupal-console/issues/3093

**Comment by alvar0hurtad0** [comment]
Just push forward the problem one version, maybe the best is wait to the library version on console is updated.

**Review by pfrenssen — CHANGES_REQUESTED** [review]
This is not ideal, since it will cause drupal-console to be installed on production for all projects that use OG. Drupal-console is a great tool but it is better kept strictly on development environments until its stability and test coverage improves. 

Can you please revert this? It's out of scope for this issue, the CI failure is currently being tackled in another issue. I'm on my phone so I can't link it easily.

**Comment by alvar0hurtad0** [comment]
Ok, you're right :)

Thanks

**Comment by pfrenssen** [comment]
Thanks! The CI failure is in the meanwhile also fixed, see #235.

**Comment by pfrenssen** [comment]
Great, the test is green, merging. Thanks!

**Comment by alvar0hurtad0** [comment]
Thank you :)

**Comment by amitaibu** [comment]
Thanks guys!

**Pull request merged**
