### PR TITLE
Provide a helper method to load roles by group type

### PR DESCRIPTION
**Pull request by pfrenssen**
This has been split off from #244.

Let's provide a simple helper method that allows to load all OgRole entities that belong to a given group type.

### CODE REVIEW

**Comment by pfrenssen** [comment]
This is blocked on #286 which fixes a failure that affects the current HEAD.

**Comment by amitaibu** [comment]
What is the use case for this?

**Comment by pfrenssen** [comment]
The use case for this in #244 is that it is providing a form to add new roles to a group type. In order to generate the form it needs to retrieve the roles that are associated with the group type:

https://github.com/ec-europa/og/blob/ISAICP-2709/src/Form/OgAddMultipleRolesForm.php#L27

I figured this could be useful for all cases where somebody needs to get the list of roles that exist for a certain group type, but this is just a minor DX addition so I can live without it.

I also see that the method name `OgRole::loadRolesByGroupType()` is not consistent with the other helper method (`OgRole::loadByGroupAndName()`). If we do decide to keep this then we can maybe change the name to `loadByGroupType()` or `loadByGroupEntityTypeAndBundle()`.

**Comment by amitaibu** [comment]
Yeah, let's go ahead with the proposed renaming.

**Comment by pfrenssen** [comment]
Renamed the method.

**Comment by amitaibu** [comment]
Thanks.

**Pull request merged**
