### PR TITLE
Fix PHP warning in MembershipManager::getGroupIds()

### PR DESCRIPTION
**Pull request by zerolab**
On PHP 7.0.x, create a group content node.

Go to edit the node:

```
Notice: Undefined index: target_id in Drupal\og\MembershipManager->Drupal\og\{closure}() (line 227 of modules/contrib/og/src/MembershipManager.php).
Drupal\og\MembershipManager->Drupal\og\{closure}(Array)
array_map(Object, Array) (Line: 228)
Drupal\og\MembershipManager->getGroupIds(Object, NULL, NULL) (Line: 268)
Drupal\og\MembershipManager->getGroups(Object) (Line: 93)
Drupal\og\Plugin\OgGroupResolver\RouteGroupContentResolver->resolve(Object) (Line: 144)
Drupal\og\ContextProvider\OgContext->getBestCandidate() (Line: 100)
Drupal\og\ContextProvider\OgContext->getOgContext() (Line: 79)
Drupal\og\ContextProvider\OgContext->getRuntimeContexts(Array) (Line: 173)
Drupal\og\ContextProvider\OgContext->getGroup() (Line: 54)
```

### CODE REVIEW

**Comment by zerolab** [comment]
All tests are green, so ready for review

**Comment by amitaibu** [comment]
Thanks! Would it be possible to add some test to assert/ prevent regressions?

**Comment by zerolab** [comment]
I am not entirely sure how to replicate this. I suspect it comes from the complex widget. Some times, if the content creator has permissions to just create content within the group, the group is added to the "other groups" bit of the complex widget.

Will have to look tonight.

**Comment by amitaibu** [comment]
Oh, in that case https://github.com/Gizra/og/pull/181 might help with "fixing" the cause

**Comment by pfrenssen** [comment]
Closing this, this error is occurring in code that will be removed in #181.

**Pull request closed without merging**
