### PR TITLE
Rules integration: Get group members with role

### PR DESCRIPTION
**Pull request by mxr576**
Pull request with changes shipped by this patch from D.o.:

https://www.drupal.org/node/2299353#comment-11535307

### CODE REVIEW

**Comment by mxr576** [comment]
Is there a reason why is this PR still has not been accepted?

**Comment by mxr576** [comment]
Triggered Travis to re-check this PR by closing and reopening it. I hope Travis is working now.

**Comment by scotself** [comment]
Wonderful and extremely useful patch!! Let's get this in, please!

**Comment by claudiu-cristea** [comment]
Since https://www.drupal.org/project/og/issues/3467694 was merged into the `8.x-1.x` branch, the development has been moved to https://www.drupal.org/project/og. If this change is still actual, please open an issue at https://www.drupal.org/project/issues/og and provide there a _merge request_ similar with this pull request.

Thank you for contributing to Organic groups module.

**Pull request closed without merging**
