### PR TITLE
Amitai's PR 181 updated w latest 8.x-1.x

### PR DESCRIPTION
**Pull request by damienmckenna**
This is just Amitai's PR #181 updated with the latest changes from 8.x-1.x.

### CODE REVIEW

**Comment by damienmckenna** [comment]
Here's the changes in patch format, for anyone who needs it.
[og-558.patch.txt](https://github.com/Gizra/og/files/3433810/og-558.patch.txt)

**Comment by damienmckenna** [comment]
A correct patch (-:
[og-558-correct.patch.txt](https://github.com/Gizra/og/files/3433827/og-558-correct.patch.txt)

**Comment by MPParsley** [comment]
@damienmckenna, could you open a PR against amitaibu:160-remove-complex-widget?

**Comment by MPParsley** [comment]
Resolved merge conflict caused by #575.

Removed:
```
field.widget.settings.og_complex:
  type: field.widget.settings.entity_reference_autocomplete
  label: 'OG Group Audience field widget'
```

**Comment by MPParsley** [comment]
See #570.

**Pull request closed without merging**
