### PR TITLE
Fix PHP_CodeSniffer warnings

### PR DESCRIPTION
**Pull request by pfrenssen**
There was an update of Coder that detects some new coding standards failures.

### CODE REVIEW

**Comment by amitaibu** [comment]
Didn't miss the irony -- At least the sniffer is fixed 😆 

build__707_-_gizra_og_-_travis_ci

**Comment by pfrenssen** [comment]
Ha!! I only ran codesniffer locally, didn't check the other tests :grin: 

I'll have a look tomorrow at the failures.

**Comment by pfrenssen** [comment]
Fixed the failures, ready for review!

**Comment by amitaibu** [comment]
Thanks!

**Comment by amitaibu** [comment]
Oh, I'm not on my computer - so I'll push in the evening to the d.o. and amitaibu/og as-well

**Comment by amitaibu** [comment]
pushed

**Pull request merged**
