### PR TITLE
[Drupal 10.2] Using a translatable string as a category for field type is deprecated

### PR DESCRIPTION
**Pull request by claudiu-cristea**
See https://www.drupal.org/node/3375748

### CODE REVIEW

**Comment by joelpittet** [comment]
@claudiu-cristea Are there any negatives for pre 10.2 with this change? Looks good I just am not sure where that is used in 10.1 off hand

**Comment by claudiu-cristea** [comment]
The only thing I can see is that the category will be rendered as lowercase and untranslated in the admin UI.

There's no way to fix this in a definitions alter hook because that acts after the depreciation error message has been broadcasted.

**Comment by amitaibu** [comment]
@bboro ^^

**Comment by claudiu-cristea** [comment]
Since https://www.drupal.org/project/og/issues/3467694 was merged into the `8.x-1.x` branch, the development has been moved to https://www.drupal.org/project/issues/og. If this change is still actual, please open an issue at https://www.drupal.org/project/issues/og and provide there a _merge request_ similar with this pull request.

Thank you for contributing to Organic groups module.

**Pull request closed without merging**
