### PR TITLE
Issue #34: Trimmed version of menu_get_path() as comparison.

### PR DESCRIPTION
**Pull request by kaaresl**
This has the same functionality as pre #28, only using a really basic version of menu_get_item.
### Remaining tasks
- Tests needed (I'm not the guy here)
- ~~Maybe extract this code to an internal function.~~
- ~~Add static cache of found menu router items?~~
- ~~Rename function to `_og_context_menu_get_(unprocessed|untranslated|raw)_item()`~~ (Went for `_og_context_menu_get_untranslated_item()` to better match the fact that `_menu_translate` isn't called).

### CODE REVIEW

**Comment by kaaresl** [comment]
Other than missing tests, I think this is review-worthy.

**Comment by amitaibu** [comment]
@HelenaEksler can you please do a first review. Bonus points for a test

**Comment by amitaibu** [comment]
I've reverted 66d3b723b6c305006acf5204fca27d7d2f30bc26 - @kaaresl can you please re-roll

**Comment by kaaresl** [comment]
Did a `git rebase git rebase upstream/7.x-2.x` which caused some code leakage from #29, but otherwise, `og_context_determine_context()` is the same as prior to the revert of #29. So all in all, this PR is an alternative solution of 29 :-)

**Comment by kaaresl** [comment]
Oh, this patch isn't ready. The parameter `$item` in `og_context_determine_context()` is ignored.

**Comment by kaaresl** [comment]
That "code leakage" was not at all code leakage. It was removed in #29, hence the `$item` parameter got ignored. It's back and things should hopefully work with menu items given as parameter without calling `_og_context_menu_get_untranslated_item()`. Only `$item['path']` is ever used and this isn't touched in `_menu_translate()`.

**Comment by kaaresl** [comment]
This PR and commit stack got a bit messy. A clean diff using `git diff -u --stat upstream/7.x-2.x` is available here: https://gist.github.com/kaaresl/dd03248fb8c02633c1fc

**Comment by kaaresl** [comment]
Updated gist to match latest commit. Needs review.

**Comment by amitaibu** [comment]
PR still seems to have non-related code. It should show only your own diff (you can always use `push -f` if you must )

**Comment by kaaresl** [comment]
Forget this PR and head over to #40.

**Pull request closed without merging**
