### PR TITLE
Remove unused OgPermissionHandler service

### PR DESCRIPTION
**Pull request by pfrenssen**
An earlier implementation a service that handled OG permissions using YAML files is still present in the repository. This is no longer used, it is superseded by `OgPermissionManager`. Let's get rid of it.

### CODE REVIEW

**Comment by amitaibu** [comment]
Needs a re-roll

**Comment by amitaibu** [comment]
(I'll re-roll)

**Comment by amitaibu** [comment]
btw, this made me think. Nothing that I would change now, but as an idea - The current implementation we have - couldn't we keep declaring the permissions via yaml, and have our `GroupPermission` and `GroupContentPermission`?

So we'd still have the convenience of config yaml files, and the safety of the wrapping objects?

**Comment by amitaibu** [comment]
@pfrenssen ^^

**Comment by amitaibu** [comment]
- Thanks :)

**Comment by pfrenssen** [comment]
I think it could be possible to do this, have a YAML file that declares permissions, and load these in addition to the ones that are provided by the event. We'd need to think a bit for the structure of the YAML file but it should be no problem for declaring simple static permissions.

**Comment by amitaibu** [comment]
Opened #200

**Pull request merged**
