### PR TITLE
Tests fixed for #231

### PR DESCRIPTION
**Pull request by DiDebru**
I removed all deprecations in the test and the PHP 5.6 TestSuite as it will be EOL in 2019 see http://php.net/supported-versions.php

### CODE REVIEW

**Comment by MPParsley** [comment]
@Insasse, could you resolve the conflicts?

**Comment by pfrenssen** [comment]
It seems like the rebase has caused this to go slightly out of scope :)

**Comment by DiDebru** [comment]
Yeah it seems so :D

**Comment by MPParsley** [comment]
@Insasse, is this still relevant? #231 is currently all green.

**Comment by MPParsley** [comment]
#231 is still green, you may want to open a new PR against jludwig:og-membership-ui if you want to add something.

**Pull request closed without merging**
