### PR TITLE
Resolves #102: Clarify error thrown by og_group().

### LINKED ISSUE #102: Unclear error messaging
Relates to [Migration errors related to field cardinality](https://www.drupal.org/node/2657672)

### PR DESCRIPTION
**Pull request by grasmash**

### CODE REVIEW

**Comment by grasmash** [comment]
Looks like Travis CI is hitting an unrelated error:

```
Discovery of channel "pear.drush.org" failed (channel-add: Cannot open "https://pear.drush.org/channel.xml" (Connection to `pear.drush.org:443' failed: php_network_getaddresses: getaddrinfo failed: Name or service not known))
```

**Comment by grasmash** [comment]
You may want to consider installing drush through composer rather than through pear. E.g., add this to .travis.yml:

```
  - composer global require drush/drush:7.1.0
  - export PATH="$HOME/.composer/vendor/bin:$PATH
```

This will get rid of your pear errors.

You should also disable xdebug on travis to speed up your test runs using:

```
  - phpenv config-rm xdebug.ini
```

**Comment by grasmash** [comment]
See #104 for PR containing .travis.yml changes.

**Comment by claudiu-cristea** [comment]
Since https://www.drupal.org/project/og/issues/3467694 was merged into the `8.x-1.x` branch, the development has been moved to https://www.drupal.org/project/og. If this change is still actual, please open an issue at https://www.drupal.org/project/issues/og and provide there a _merge request_ similar with this pull request.

Thank you for contributing to Organic groups module.

**Pull request closed without merging**
